name: build and test feature branch
on:
  push:
    branches:
      - feature/*
jobs: 
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: pull and checkout from git repository

        run: |
           echo "pulling and checking out from git repository"

      - name: setup java 17 
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'

      - name: build with maven
        run: |
          mvn clean install
          echo "build with maven"
    
      